name: DiscordBridge
version: 2.8.0
main: com.khangsmp.discordbridge.DiscordBridgePlugin
api-version: '1.16'
softdepend: [floodgate, Geyser-Spigot]
description: Cau noi chat hai chieu Minecraft <-> Discord cho KhangSMP
author: KhangSMP
commands:
  discordbridge:
    description: Quan ly plugin DiscordBridge
    usage: /discordbridge reload
    aliases: [dcbridge, dcb]
    permission: discordbridge.admin
permissions:
  discordbridge.admin:
    description: Quyen reload cau hinh DiscordBridge
    default: op
